services:
  go-api:
    build:
      context: ./services/go-api
      dockerfile: Dockerfile
    container_name: interseguro-go-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://neondb_owner:npg_IACVv2Be4zSg@ep-cool-band-b506sy3m-pooler.c-7.us-east-2.aws.neon.tech/matrix_challenge_db?sslmode=require
      - NODE_API_URL=http://node-api:4000
      - JWT_SECRET=interseguro_challenge_secure_jwt_secret_key_2026
      - ENABLE_AUTH=false
    depends_on:
      - node-api
    networks:
      - interseguro-network

  node-api:
    build:
      context: ./services/node-api
      dockerfile: Dockerfile
    container_name: interseguro-node-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    networks:
      - interseguro-network

networks:
  interseguro-network:
    driver: bridge
